#pragma once
#ifndef SCENE_TYPES
#define SCENE_TYPES
namespace SCENE_TYPE
{
  enum ID {MENU,
    MODEL_TYPE_SELECT,
    PLAY_MODEL_SELECT,
    DATASET_MENU,
    DATASET_BUILDER,
    DATASET_BUILDER_PIX2PIX,
    DATASET_PROCESSESOR,
    DATASET_SELECTOR,
    ARCHITECTURE_MENU,
    ARCHITECTURE_BUILDER,
    ARCHITECTURE_SELECT,
    HYPERPARAMETER_SELECT,
    TRAIN,
    INTERACT_MENU,
    EXPLORE_LATENT,
    INTERACT,
    INTERACTGAN,
    INTERACTPIX2PIX
    };
}
#endif


#ifndef MODEL_TYPES
#define MODEL_TYPES
namespace MODEL_TYPE
{
  enum ID {GAN, PIX2PIX, CUSTOM
    };
}
#endif
